name: bilivideo_down
description: "A new Flutter project."
publish_to: "none" 

version: 1.0.0+1

environment:
  sdk: ">=3.3.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.4.2+1
  common_utils: 2.1.0
  window_manager: 0.3.6
  go_router: ^13.2.4
  get: ^4.6.6
  path_provider: ^2.1.3
  file_picker: ^8.0.0+1
  sqflite: ^2.3.2
  sqflite_common_ffi: ^2.3.3 # 数据库
  video_player: ^2.8.6
  sp_util: ^2.0.3
  video_player_win: ^2.3.6
  permission_handler: ^11.3.1
  icons_launcher: ^2.1.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/flutter.db

 